# Generated by Django 2.0.7 on 2018-07-20 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20180720_0855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='Car',
        ),
    ]
