# Generated by Django 2.0.7 on 2018-07-21 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_carimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(default='', max_length=32)),
                ('name', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.CharField(default='', max_length=32)),
                ('name', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='forloan',
            field=models.BooleanField(default=False, verbose_name='На продажу'),
        ),
        migrations.AddField(
            model_name='car',
            name='gosnomer',
            field=models.CharField(default='', max_length=64, verbose_name='Госномер'),
        ),
        migrations.AddField(
            model_name='car',
            name='i_d',
            field=models.CharField(default='', max_length=32, verbose_name='Идентификатор'),
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default='', max_length=64, verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='car',
            name='used',
            field=models.BooleanField(default=False, verbose_name='С пробегом'),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(default='', max_length=64, verbose_name='VIN'),
        ),
        migrations.AddField(
            model_name='company',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.CompanyGroup'),
        ),
        migrations.AddField(
            model_name='car',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.Company', verbose_name='date created'),
        ),
    ]
