# Generated by Django 2.0.7 on 2018-07-21 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_auto_20180721_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company',
            new_name='group',
        ),
    ]
